version: "3"

tasks:
  format:
    cmd: uv run ruff format .
    desc: Format Python code with ruff

  check:
    desc: Check Python code with ruff and ty
    cmds:
      - uv run ruff check --fix .
      - uvx ty check .

  test:
    cmd: uv run pytest tests/ --cov=pragma_sdk --cov-report=term-missing {{.CLI_ARGS}}
    desc: Run all tests with coverage
